export enum TermId {
  Pin = 'pin',
  Peh = 'peh',
  Xi = 'xi',
  Ees = 'ees',
  Emax = 'emax',
  Eup = 'eup',
  Elow = 'elow',
  Prx = 'prx',
  Ptx = 'ptx',
  Psl = 'psl',
  Em = 'em',
  Dcm = 'dcm',
  Paging = 'paging',
  Cbra = 'cbra',
  Ao = 'ao',
  Msg1 = 'msg1',
  Msg2 = 'msg2',
  Msg3 = 'msg3',
  Paccess = 'paccess',
  Eligible = 'eligible',
  Collision = 'collision',
  Singleton = 'singleton',
  Tpg = 'tpg',
  TonTimer = 'tonTimer',
  TonDcm = 'tonDcm',
  Group = 'group',
  T50 = 't50',
  T90 = 't90',
  T99 = 't99',
}

export enum ViewId {
  Factory = 'factory',
  Inspector = 'inspector',
  Energy = 'energy',
  Cbra = 'cbra',
  Fig5b = 'fig5b',
  Metrics = 'metrics',
  StrategyMap = 'strategyMap',
}

export enum SourceType {
  Paper = 'paper',
  Digitized = 'digitized',
  Assumption = 'assumption',
}

export const TERM_SOURCE: Record<TermId, SourceType> = {
  [TermId.Pin]: SourceType.Digitized,
  [TermId.Peh]: SourceType.Paper,
  [TermId.Xi]: SourceType.Paper,
  [TermId.Ees]: SourceType.Paper,
  [TermId.Emax]: SourceType.Paper,
  [TermId.Eup]: SourceType.Paper,
  [TermId.Elow]: SourceType.Paper,
  [TermId.Prx]: SourceType.Paper,
  [TermId.Ptx]: SourceType.Paper,
  [TermId.Psl]: SourceType.Paper,
  [TermId.Em]: SourceType.Paper,
  [TermId.Dcm]: SourceType.Paper,
  [TermId.Paging]: SourceType.Paper,
  [TermId.Cbra]: SourceType.Paper,
  [TermId.Ao]: SourceType.Paper,
  [TermId.Msg1]: SourceType.Paper,
  [TermId.Msg2]: SourceType.Paper,
  [TermId.Msg3]: SourceType.Paper,
  [TermId.Paccess]: SourceType.Assumption,
  [TermId.Eligible]: SourceType.Assumption,
  [TermId.Collision]: SourceType.Paper,
  [TermId.Singleton]: SourceType.Paper,
  [TermId.Tpg]: SourceType.Paper,
  [TermId.TonTimer]: SourceType.Paper,
  [TermId.TonDcm]: SourceType.Paper,
  [TermId.Group]: SourceType.Assumption,
  [TermId.T50]: SourceType.Paper,
  [TermId.T90]: SourceType.Paper,
  [TermId.T99]: SourceType.Paper,
}
